// Code generated by hand for gomock.
// DO NOT EDIT MANUALLY unless you know what you're doing.

package reservation

import (
	"reflect"
	"time"

	"github.com/golang/mock/gomock"
)

// MockReservationRepository is a mock of ReservationRepository interface.
type MockReservationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockReservationRepositoryMockRecorder
}

// MockReservationRepositoryMockRecorder is the mock recorder for MockReservationRepository.
type MockReservationRepositoryMockRecorder struct {
	mock *MockReservationRepository
}

// NewMockReservationRepository creates a new mock instance.
func NewMockReservationRepository(ctrl *gomock.Controller) *MockReservationRepository {
	mock := &MockReservationRepository{ctrl: ctrl}
	mock.recorder = &MockReservationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReservationRepository) EXPECT() *MockReservationRepositoryMockRecorder {
	return m.recorder
}

// CreateOrderWithLock mocks base method.
func (m *MockReservationRepository) CreateOrderWithLock(order *ReservationOrder, slots []ReservationSlot) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrderWithLock", order, slots)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOrderWithLock indicates an expected call of CreateOrderWithLock.
func (mr *MockReservationRepositoryMockRecorder) CreateOrderWithLock(order, slots interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrderWithLock", reflect.TypeOf((*MockReservationRepository)(nil).CreateOrderWithLock), order, slots)
}

// FindByOrderID mocks base method.
func (m *MockReservationRepository) FindByOrderID(id uint) (*ReservationOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByOrderID", id)
	ret0, _ := ret[0].(*ReservationOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByOrderID indicates an expected call of FindByOrderID.
func (mr *MockReservationRepositoryMockRecorder) FindByOrderID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByOrderID", reflect.TypeOf((*MockReservationRepository)(nil).FindByOrderID), id)
}

// FindByID mocks base method (alias for FindByOrderID).
func (m *MockReservationRepository) FindByID(id uint) (*ReservationOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(*ReservationOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockReservationRepositoryMockRecorder) FindByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockReservationRepository)(nil).FindByID), id)
}

// FindByOpenID mocks base method.
func (m *MockReservationRepository) FindByOpenID(openid string) ([]*ReservationOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByOpenID", openid)
	ret0, _ := ret[0].([]*ReservationOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByOpenID indicates an expected call of FindByOpenID.
func (mr *MockReservationRepositoryMockRecorder) FindByOpenID(openid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByOpenID", reflect.TypeOf((*MockReservationRepository)(nil).FindByOpenID), openid)
}

// FindSlotsByTimeRange mocks base method.
func (m *MockReservationRepository) FindSlotsByTimeRange(start, end time.Time) ([]ReservationSlot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindSlotsByTimeRange", start, end)
	ret0, _ := ret[0].([]ReservationSlot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindSlotsByTimeRange indicates an expected call of FindSlotsByTimeRange.
func (mr *MockReservationRepositoryMockRecorder) FindSlotsByTimeRange(start, end interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindSlotsByTimeRange", reflect.TypeOf((*MockReservationRepository)(nil).FindSlotsByTimeRange), start, end)
}

// UpdateSlotStatus mocks base method.
func (m *MockReservationRepository) UpdateSlotStatus(slotID uint, status int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSlotStatus", slotID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSlotStatus indicates an expected call of UpdateSlotStatus.
func (mr *MockReservationRepositoryMockRecorder) UpdateSlotStatus(slotID, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSlotStatus", reflect.TypeOf((*MockReservationRepository)(nil).UpdateSlotStatus), slotID, status)
}

// CancelOrder mocks base method.
func (m *MockReservationRepository) CancelOrder(orderID uint, openid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelOrder", orderID, openid)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelOrder indicates an expected call of CancelOrder.
func (mr *MockReservationRepositoryMockRecorder) CancelOrder(orderID, openid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelOrder", reflect.TypeOf((*MockReservationRepository)(nil).CancelOrder), orderID, openid)
}
