// Code generated by hand for gomock.
package review

import (
	"reflect"
	"time"

	reservationdb "reservation-sys/pkg/reservationdb"

	"github.com/golang/mock/gomock"
)

// MockRepository is a mock of reservationdb.Repository interface for admin review tests.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CreateOrderWithLock mocks base method.
func (m *MockRepository) CreateOrderWithLock(order *reservationdb.ReservationOrder, slots []reservationdb.ReservationSlot) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrderWithLock", order, slots)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockRepositoryMockRecorder) CreateOrderWithLock(order, slots any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrderWithLock", reflect.TypeOf((*MockRepository)(nil).CreateOrderWithLock), order, slots)
}

// FindOrderByID mocks base method.
func (m *MockRepository) FindOrderByID(id uint) (*reservationdb.ReservationOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOrderByID", id)
	ret0, _ := ret[0].(*reservationdb.ReservationOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockRepositoryMockRecorder) FindOrderByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOrderByID", reflect.TypeOf((*MockRepository)(nil).FindOrderByID), id)
}

// FindOrdersByOpenID mocks base method.
func (m *MockRepository) FindOrdersByOpenID(openid string) ([]*reservationdb.ReservationOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOrdersByOpenID", openid)
	ret0, _ := ret[0].([]*reservationdb.ReservationOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockRepositoryMockRecorder) FindOrdersByOpenID(openid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOrdersByOpenID", reflect.TypeOf((*MockRepository)(nil).FindOrdersByOpenID), openid)
}

// ListOrders mocks base method.
func (m *MockRepository) ListOrders(statuses []int, page, pageSize int) ([]*reservationdb.ReservationOrder, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrders", statuses, page, pageSize)
	ret0, _ := ret[0].([]*reservationdb.ReservationOrder)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

func (mr *MockRepositoryMockRecorder) ListOrders(statuses, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrders", reflect.TypeOf((*MockRepository)(nil).ListOrders), statuses, page, pageSize)
}

// UpdateOrderStatus mocks base method.
func (m *MockRepository) UpdateOrderStatus(orderID uint, fromStatus, toStatus int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrderStatus", orderID, fromStatus, toStatus)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockRepositoryMockRecorder) UpdateOrderStatus(orderID, fromStatus, toStatus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrderStatus", reflect.TypeOf((*MockRepository)(nil).UpdateOrderStatus), orderID, fromStatus, toStatus)
}

// CancelOrder mocks base method.
func (m *MockRepository) CancelOrder(orderID uint, openid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelOrder", orderID, openid)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockRepositoryMockRecorder) CancelOrder(orderID, openid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelOrder", reflect.TypeOf((*MockRepository)(nil).CancelOrder), orderID, openid)
}

// FindSlotsByTimeRange mocks base method.
func (m *MockRepository) FindSlotsByTimeRange(start, end time.Time) ([]reservationdb.ReservationSlot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindSlotsByTimeRange", start, end)
	ret0, _ := ret[0].([]reservationdb.ReservationSlot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockRepositoryMockRecorder) FindSlotsByTimeRange(start, end any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindSlotsByTimeRange", reflect.TypeOf((*MockRepository)(nil).FindSlotsByTimeRange), start, end)
}

// FindSlotsWithOpenIDByTimeRange mocks base method.
func (m *MockRepository) FindSlotsWithOpenIDByTimeRange(start, end time.Time) ([]reservationdb.SlotWithOpenID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindSlotsWithOpenIDByTimeRange", start, end)
	ret0, _ := ret[0].([]reservationdb.SlotWithOpenID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindSlotsWithOpenIDByTimeRange indicates an expected call of FindSlotsWithOpenIDByTimeRange.
func (mr *MockRepositoryMockRecorder) FindSlotsWithOpenIDByTimeRange(start, end any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindSlotsWithOpenIDByTimeRange", reflect.TypeOf((*MockRepository)(nil).FindSlotsWithOpenIDByTimeRange), start, end)
}

// UpdateSlotStatus mocks base method.
func (m *MockRepository) UpdateSlotStatus(slotID uint, status int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSlotStatus", slotID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockRepositoryMockRecorder) UpdateSlotStatus(slotID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSlotStatus", reflect.TypeOf((*MockRepository)(nil).UpdateSlotStatus), slotID, status)
}

// SetSlotPassword mocks base method.
func (m *MockRepository) SetSlotPassword(slotID uint, password string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSlotPassword", slotID, password)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockRepositoryMockRecorder) SetSlotPassword(slotID, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSlotPassword", reflect.TypeOf((*MockRepository)(nil).SetSlotPassword), slotID, password)
}

// CreateReviewRecord mocks base method.
func (m *MockRepository) CreateReviewRecord(record *reservationdb.ReviewRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateReviewRecord", record)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockRepositoryMockRecorder) CreateReviewRecord(record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateReviewRecord", reflect.TypeOf((*MockRepository)(nil).CreateReviewRecord), record)
}

// FindReviewRecordsByOrderID mocks base method.
func (m *MockRepository) FindReviewRecordsByOrderID(orderID uint) ([]reservationdb.ReviewRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindReviewRecordsByOrderID", orderID)
	ret0, _ := ret[0].([]reservationdb.ReviewRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockRepositoryMockRecorder) FindReviewRecordsByOrderID(orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindReviewRecordsByOrderID", reflect.TypeOf((*MockRepository)(nil).FindReviewRecordsByOrderID), orderID)
}
