// Code generated by hand for gomock.
package review

import (
	"context"
	"reflect"

	pb "reservation-sys/service/gateway/api/gen/notification"

	"github.com/golang/mock/gomock"
	"google.golang.org/grpc"
)

// MockNotificationServiceClient is a mock of pb.NotificationServiceClient interface.
type MockNotificationServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationServiceClientMockRecorder
}

// MockNotificationServiceClientMockRecorder is the mock recorder.
type MockNotificationServiceClientMockRecorder struct {
	mock *MockNotificationServiceClient
}

// NewMockNotificationServiceClient creates a new mock instance.
func NewMockNotificationServiceClient(ctrl *gomock.Controller) *MockNotificationServiceClient {
	mock := &MockNotificationServiceClient{ctrl: ctrl}
	mock.recorder = &MockNotificationServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationServiceClient) EXPECT() *MockNotificationServiceClientMockRecorder {
	return m.recorder
}

// SendApprovalNotification mocks base method.
func (m *MockNotificationServiceClient) SendApprovalNotification(ctx context.Context, in *pb.ApprovalNotificationReq, opts ...grpc.CallOption) (*pb.NotificationResp, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SendApprovalNotification", varargs...)
	ret0, _ := ret[0].(*pb.NotificationResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendApprovalNotification indicates an expected call.
func (mr *MockNotificationServiceClientMockRecorder) SendApprovalNotification(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendApprovalNotification", reflect.TypeOf((*MockNotificationServiceClient)(nil).SendApprovalNotification), varargs...)
}

// SendRejectionNotification mocks base method.
func (m *MockNotificationServiceClient) SendRejectionNotification(ctx context.Context, in *pb.RejectionNotificationReq, opts ...grpc.CallOption) (*pb.NotificationResp, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SendRejectionNotification", varargs...)
	ret0, _ := ret[0].(*pb.NotificationResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendRejectionNotification indicates an expected call.
func (mr *MockNotificationServiceClientMockRecorder) SendRejectionNotification(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendRejectionNotification", reflect.TypeOf((*MockNotificationServiceClient)(nil).SendRejectionNotification), varargs...)
}
