// Code generated by MockGen. DO NOT EDIT.
// Source: internal/auth/service.go

// Package auth is a generated GoMock package.
package auth

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockOAuthClient is a mock of OAuthClient interface.
type MockOAuthClient struct {
	ctrl     *gomock.Controller
	recorder *MockOAuthClientMockRecorder
}

// MockOAuthClientMockRecorder is the mock recorder for MockOAuthClient.
type MockOAuthClientMockRecorder struct {
	mock *MockOAuthClient
}

// NewMockOAuthClient creates a new mock instance.
func NewMockOAuthClient(ctrl *gomock.Controller) *MockOAuthClient {
	mock := &MockOAuthClient{ctrl: ctrl}
	mock.recorder = &MockOAuthClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOAuthClient) EXPECT() *MockOAuthClientMockRecorder {
	return m.recorder
}

// GetUserAccessToken mocks base method.
func (m *MockOAuthClient) GetUserAccessToken(code string) (*OAuthAccessTokenResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserAccessToken", code)
	ret0, _ := ret[0].(*OAuthAccessTokenResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserAccessToken indicates an expected call of GetUserAccessToken.
func (mr *MockOAuthClientMockRecorder) GetUserAccessToken(code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserAccessToken", reflect.TypeOf((*MockOAuthClient)(nil).GetUserAccessToken), code)
}

// GetUserInfo mocks base method.
func (m *MockOAuthClient) GetUserInfo(openid string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserInfo", openid)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetUserInfo indicates an expected call of GetUserInfo.
func (mr *MockOAuthClientMockRecorder) GetUserInfo(openid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserInfo", reflect.TypeOf((*MockOAuthClient)(nil).GetUserInfo), openid)
}

// MockUserInfoProvider is a mock of UserInfoProvider interface.
type MockUserInfoProvider struct {
	ctrl     *gomock.Controller
	recorder *MockUserInfoProviderMockRecorder
}

// MockUserInfoProviderMockRecorder is the mock recorder for MockUserInfoProvider.
type MockUserInfoProviderMockRecorder struct {
	mock *MockUserInfoProvider
}

// NewMockUserInfoProvider creates a new mock instance.
func NewMockUserInfoProvider(ctrl *gomock.Controller) *MockUserInfoProvider {
	mock := &MockUserInfoProvider{ctrl: ctrl}
	mock.recorder = &MockUserInfoProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserInfoProvider) EXPECT() *MockUserInfoProviderMockRecorder {
	return m.recorder
}

// GetUserInfo mocks base method.
func (m *MockUserInfoProvider) GetUserInfo(openid string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserInfo", openid)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetUserInfo indicates an expected call of GetUserInfo.
func (mr *MockUserInfoProviderMockRecorder) GetUserInfo(openid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserInfo", reflect.TypeOf((*MockUserInfoProvider)(nil).GetUserInfo), openid)
}
