// Code generated by hand for gomock.
package auth

import (
	"context"
	"reflect"

	pb "reservation-sys/service/gateway/api/gen/account"

	"github.com/golang/mock/gomock"
	"google.golang.org/grpc"
)

// MockAccountServiceClient is a mock of pb.AccountServiceClient interface.
type MockAccountServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockAccountServiceClientMockRecorder
}

// MockAccountServiceClientMockRecorder is the mock recorder.
type MockAccountServiceClientMockRecorder struct {
	mock *MockAccountServiceClient
}

// NewMockAccountServiceClient creates a new mock instance.
func NewMockAccountServiceClient(ctrl *gomock.Controller) *MockAccountServiceClient {
	mock := &MockAccountServiceClient{ctrl: ctrl}
	mock.recorder = &MockAccountServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountServiceClient) EXPECT() *MockAccountServiceClientMockRecorder {
	return m.recorder
}

// VerifyAdmin mocks base method.
func (m *MockAccountServiceClient) VerifyAdmin(ctx context.Context, in *pb.VerifyAdminReq, opts ...grpc.CallOption) (*pb.VerifyAdminResp, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "VerifyAdmin", varargs...)
	ret0, _ := ret[0].(*pb.VerifyAdminResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyAdmin indicates an expected call of VerifyAdmin.
func (mr *MockAccountServiceClientMockRecorder) VerifyAdmin(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyAdmin", reflect.TypeOf((*MockAccountServiceClient)(nil).VerifyAdmin), varargs...)
}
