// Code generated by hand for gomock.
// DO NOT EDIT MANUALLY unless you know what you are doing.

package reservation

import (
	"reflect"
	"time"

	reservationdb "reservation-sys/pkg/reservationdb"

	"github.com/golang/mock/gomock"
)

// MockReservationRepository is a mock of reservationdb.Repository interface.
type MockReservationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockReservationRepositoryMockRecorder
}

// MockReservationRepositoryMockRecorder is the mock recorder for MockReservationRepository.
type MockReservationRepositoryMockRecorder struct {
	mock *MockReservationRepository
}

// NewMockReservationRepository creates a new mock instance.
func NewMockReservationRepository(ctrl *gomock.Controller) *MockReservationRepository {
	mock := &MockReservationRepository{ctrl: ctrl}
	mock.recorder = &MockReservationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReservationRepository) EXPECT() *MockReservationRepositoryMockRecorder {
	return m.recorder
}

// CreateOrderWithLock mocks base method.
func (m *MockReservationRepository) CreateOrderWithLock(order *reservationdb.ReservationOrder, slots []reservationdb.ReservationSlot) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrderWithLock", order, slots)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOrderWithLock indicates an expected call of CreateOrderWithLock.
func (mr *MockReservationRepositoryMockRecorder) CreateOrderWithLock(order, slots any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrderWithLock", reflect.TypeOf((*MockReservationRepository)(nil).CreateOrderWithLock), order, slots)
}

// FindOrderByID mocks base method.
func (m *MockReservationRepository) FindOrderByID(id uint) (*reservationdb.ReservationOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOrderByID", id)
	ret0, _ := ret[0].(*reservationdb.ReservationOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOrderByID indicates an expected call of FindOrderByID.
func (mr *MockReservationRepositoryMockRecorder) FindOrderByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOrderByID", reflect.TypeOf((*MockReservationRepository)(nil).FindOrderByID), id)
}

// FindOrdersByOpenID mocks base method.
func (m *MockReservationRepository) FindOrdersByOpenID(openid string) ([]*reservationdb.ReservationOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOrdersByOpenID", openid)
	ret0, _ := ret[0].([]*reservationdb.ReservationOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOrdersByOpenID indicates an expected call of FindOrdersByOpenID.
func (mr *MockReservationRepositoryMockRecorder) FindOrdersByOpenID(openid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOrdersByOpenID", reflect.TypeOf((*MockReservationRepository)(nil).FindOrdersByOpenID), openid)
}

// ListOrders mocks base method.
func (m *MockReservationRepository) ListOrders(statuses []int, page, pageSize int) ([]*reservationdb.ReservationOrder, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrders", statuses, page, pageSize)
	ret0, _ := ret[0].([]*reservationdb.ReservationOrder)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListOrders indicates an expected call of ListOrders.
func (mr *MockReservationRepositoryMockRecorder) ListOrders(statuses, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrders", reflect.TypeOf((*MockReservationRepository)(nil).ListOrders), statuses, page, pageSize)
}

// UpdateOrderStatus mocks base method.
func (m *MockReservationRepository) UpdateOrderStatus(orderID uint, fromStatus, toStatus int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrderStatus", orderID, fromStatus, toStatus)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOrderStatus indicates an expected call of UpdateOrderStatus.
func (mr *MockReservationRepositoryMockRecorder) UpdateOrderStatus(orderID, fromStatus, toStatus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrderStatus", reflect.TypeOf((*MockReservationRepository)(nil).UpdateOrderStatus), orderID, fromStatus, toStatus)
}

// CancelOrder mocks base method.
func (m *MockReservationRepository) CancelOrder(orderID uint, openid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelOrder", orderID, openid)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelOrder indicates an expected call of CancelOrder.
func (mr *MockReservationRepositoryMockRecorder) CancelOrder(orderID, openid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelOrder", reflect.TypeOf((*MockReservationRepository)(nil).CancelOrder), orderID, openid)
}

// FindSlotsByTimeRange mocks base method.
func (m *MockReservationRepository) FindSlotsByTimeRange(start, end time.Time) ([]reservationdb.ReservationSlot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindSlotsByTimeRange", start, end)
	ret0, _ := ret[0].([]reservationdb.ReservationSlot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindSlotsByTimeRange indicates an expected call of FindSlotsByTimeRange.
func (mr *MockReservationRepositoryMockRecorder) FindSlotsByTimeRange(start, end any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindSlotsByTimeRange", reflect.TypeOf((*MockReservationRepository)(nil).FindSlotsByTimeRange), start, end)
}

// UpdateSlotStatus mocks base method.
func (m *MockReservationRepository) UpdateSlotStatus(slotID uint, status int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSlotStatus", slotID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSlotStatus indicates an expected call of UpdateSlotStatus.
func (mr *MockReservationRepositoryMockRecorder) UpdateSlotStatus(slotID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSlotStatus", reflect.TypeOf((*MockReservationRepository)(nil).UpdateSlotStatus), slotID, status)
}

// SetSlotPassword mocks base method.
func (m *MockReservationRepository) SetSlotPassword(slotID uint, password string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSlotPassword", slotID, password)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetSlotPassword indicates an expected call of SetSlotPassword.
func (mr *MockReservationRepositoryMockRecorder) SetSlotPassword(slotID, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSlotPassword", reflect.TypeOf((*MockReservationRepository)(nil).SetSlotPassword), slotID, password)
}

// CreateReviewRecord mocks base method.
func (m *MockReservationRepository) CreateReviewRecord(record *reservationdb.ReviewRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateReviewRecord", record)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateReviewRecord indicates an expected call of CreateReviewRecord.
func (mr *MockReservationRepositoryMockRecorder) CreateReviewRecord(record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateReviewRecord", reflect.TypeOf((*MockReservationRepository)(nil).CreateReviewRecord), record)
}

// FindReviewRecordsByOrderID mocks base method.
func (m *MockReservationRepository) FindReviewRecordsByOrderID(orderID uint) ([]reservationdb.ReviewRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindReviewRecordsByOrderID", orderID)
	ret0, _ := ret[0].([]reservationdb.ReviewRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindReviewRecordsByOrderID indicates an expected call of FindReviewRecordsByOrderID.
func (mr *MockReservationRepositoryMockRecorder) FindReviewRecordsByOrderID(orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindReviewRecordsByOrderID", reflect.TypeOf((*MockReservationRepository)(nil).FindReviewRecordsByOrderID), orderID)
}
