// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v2/reservation/my": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取当前登录用户的所有预约记录，需要JWT认证",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "预约管理"
                ],
                "summary": "获取我的预约列表",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer",
                        "description": "Bearer JWT令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "查询成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/internal_reservation.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/internal_reservation.ReservationResp"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/internal_reservation.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/internal_reservation.Response"
                        }
                    }
                }
            }
        },
        "/api/v2/reservation/occupied": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "查询指定日期已被预约占用的时间段，需要JWT认证",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "预约管理"
                ],
                "summary": "获取已占用时间段",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer",
                        "description": "Bearer JWT令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "2026-01-01",
                        "description": "查询日期(格式: 2026-01-01)",
                        "name": "date",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "查询成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/internal_reservation.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/internal_reservation.TimeSlotResp"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/internal_reservation.Response"
                        }
                    }
                }
            }
        },
        "/api/v2/reservation/submit": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "用户提交场地预约申请，需要JWT认证",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "预约管理"
                ],
                "summary": "提交预约申请",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer",
                        "description": "Bearer JWT令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "预约提交请求",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_reservation.SubmitReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "预约申请提交成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/internal_reservation.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_reservation.ReservationResp"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/internal_reservation.Response"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/internal_reservation.Response"
                        }
                    }
                }
            }
        },
        "/api/v2/reservation/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "取消指定的预约申请，仅预约人本人可操作，需要JWT认证",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "预约管理"
                ],
                "summary": "取消预约",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer",
                        "description": "Bearer JWT令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "example": 1,
                        "description": "预约ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "取消成功",
                        "schema": {
                            "$ref": "#/definitions/internal_reservation.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/internal_reservation.Response"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/internal_reservation.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal_reservation.ReservationResp": {
            "type": "object",
            "properties": {
                "applicant_name": {
                    "description": "申请人姓名",
                    "type": "string",
                    "example": "张三"
                },
                "created_at": {
                    "description": "创建时间",
                    "type": "string",
                    "example": "2026-01-01 08:30"
                },
                "end_time": {
                    "description": "预约结束时间",
                    "type": "string",
                    "example": "2026-01-01 11:00"
                },
                "id": {
                    "description": "预约ID",
                    "type": "integer",
                    "example": 1
                },
                "order_no": {
                    "description": "订单号",
                    "type": "string",
                    "example": "R202601010900001234"
                },
                "phone": {
                    "description": "联系电话",
                    "type": "string",
                    "example": "13800138000"
                },
                "reason": {
                    "description": "预约理由",
                    "type": "string",
                    "example": "参观校史馆"
                },
                "start_time": {
                    "description": "预约开始时间",
                    "type": "string",
                    "example": "2026-01-01 09:00"
                },
                "status": {
                    "description": "预约状态: 0待审核 1已通过 2已拒绝 3已完成 4已取消",
                    "type": "integer",
                    "example": 0
                },
                "status_text": {
                    "description": "状态文本",
                    "type": "string",
                    "example": "待审核"
                }
            }
        },
        "internal_reservation.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {},
                "msg": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "internal_reservation.SubmitReq": {
            "type": "object",
            "required": [
                "alumni_association",
                "applicant_name",
                "end_time",
                "major",
                "phone",
                "reason",
                "start_time",
                "year"
            ],
            "properties": {
                "alumni_association": {
                    "description": "校友会名称",
                    "type": "string",
                    "example": "北京大学校友会"
                },
                "applicant_name": {
                    "description": "申请人姓名",
                    "type": "string",
                    "example": "张三"
                },
                "end_time": {
                    "description": "预约结束时间",
                    "type": "string",
                    "example": "2026-01-01 11:00:00"
                },
                "major": {
                    "description": "专业",
                    "type": "string",
                    "example": "计算机科学"
                },
                "phone": {
                    "description": "联系电话",
                    "type": "string",
                    "example": "13800138000"
                },
                "reason": {
                    "description": "预约理由",
                    "type": "string",
                    "maxLength": 500,
                    "example": "参观校史馆"
                },
                "start_time": {
                    "description": "预约开始时间",
                    "type": "string",
                    "example": "2026-01-01 09:00:00"
                },
                "year": {
                    "description": "入学年份",
                    "type": "integer",
                    "example": 2020
                }
            }
        },
        "internal_reservation.TimeSlotResp": {
            "type": "object",
            "properties": {
                "end_time": {
                    "description": "结束时间",
                    "type": "string",
                    "example": "2026-01-01 11:00"
                },
                "start_time": {
                    "description": "开始时间",
                    "type": "string",
                    "example": "2026-01-01 09:00"
                },
                "status": {
                    "description": "状态: pending待审核 / approved已通过",
                    "type": "string",
                    "example": "pending"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "JWT Bearer令牌认证，格式: Bearer {token}",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v2",
	Schemes:          []string{},
	Title:            "预约系统 API",
	Description:      "校友场地预约系统的后端API服务",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
